# Generated by Django 2.2.2 on 2019-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edinetcompany',
            name='jcn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='DummyFeature',
        ),
    ]
