import json
from django.test import TestCase
import edinet
from eagle.service import EDINETDocumentRegister
from eagle.models import EDINETCompany


class TestEDINETDocumentRegister(TestCase):

    def test_document_register(self):
        document_list = json.loads(LISTS.strip())
        documents = edinet.models.Documents.create(document_list)
        service = EDINETDocumentRegister()

        for d in documents.list:
            _d = service.register_document(d, "xbrl_path", "pdf_path")
            self.assertTrue(_d)

        company = EDINETCompany.objects.get(jcn="7010001054021")
        self.assertEqual("野村アセットマネジメント株式会社", company.local_name)


LISTS = """
{
    "metadata":
        {
            "title": "提出された書類を把握するためのAPI",
            "parameter":
                {
                    "date": "2019-06-04",
                    "type": "2"
                },
            "resultset":
                {
                    "count": 185
                },
            "processDateTime": "2019-06-14 00:03",
            "status": "200",
            "message": "OK"
        },
    "results": [
        {
            "seqNumber": 1,
            "docID": "S100FVD7",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G08553",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:01",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 2,
            "docID": "S100FM78",
            "edinetCode": "E12430",
            "secCode": null,
            "JCN": "8010401072159",
            "filerName": "日興アセットマネジメント株式会社",
            "fundCode": "G02803",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:01",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 3,
            "docID": "S100FVKE",
            "edinetCode": "E03610",
            "secCode": "83080",
            "JCN": "5010601039654",
            "filerName": "株式会社　りそなホールディングス",
            "fundCode": null,
            "ordinanceCode": "010",
            "formCode": "170000",
            "docTypeCode": "220",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:01",
            "docDescription": "自己株券買付状況報告書（法２４条の６第１項に基づくもの）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 4,
            "docID": "S100FP79",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G02877",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:02",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 5,
            "docID": "S100FTFN",
            "edinetCode": "E08957",
            "secCode": null,
            "JCN": "4010401049128",
            "filerName": "三井住友ＤＳアセットマネジメント株式会社",
            "fundCode": "G13314",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-09-05",
            "periodEnd": "2019-03-04",
            "submitDateTime": "2019-06-04 09:02",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第10期(平成30年9月5日－平成31年3月4日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 6,
            "docID": "S100FVR9",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G08788",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:02",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 7,
            "docID": "S100FVF0",
            "edinetCode": "E12425",
            "secCode": null,
            "JCN": "5010001048652",
            "filerName": "レッグ・メイソン・アセット・マネジメント株式会社",
            "fundCode": "G11431",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:02",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 8,
            "docID": "S100FVMU",
            "edinetCode": "E06748",
            "secCode": null,
            "JCN": "2010001049257",
            "filerName": "大和証券投資信託委託株式会社",
            "fundCode": "G01269",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-09-11",
            "periodEnd": "2019-03-11",
            "submitDateTime": "2019-06-04 09:03",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第38期(平成30年9月11日－平成31年3月11日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 9,
            "docID": "S100FVRD",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G08881",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:03",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 10,
            "docID": "S100FPO1",
            "edinetCode": "E08957",
            "secCode": null,
            "JCN": "4010401049128",
            "filerName": "三井住友ＤＳアセットマネジメント株式会社",
            "fundCode": "G13314",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:03",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 11,
            "docID": "S100FVMY",
            "edinetCode": "E06748",
            "secCode": null,
            "JCN": "2010001049257",
            "filerName": "大和証券投資信託委託株式会社",
            "fundCode": "G01269",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:03",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 12,
            "docID": "S100FVRF",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G08974",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:04",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 13,
            "docID": "S100FWCM",
            "edinetCode": "E20608",
            "secCode": null,
            "JCN": "2140001008398",
            "filerName": "株式会社神明ホールディングス",
            "fundCode": null,
            "ordinanceCode": "060",
            "formCode": "090001",
            "docTypeCode": "360",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:04",
            "docDescription": "訂正報告書（大量保有報告書・変更報告書）",
            "issuerEdinetCode": "E33000",
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": "S100EQA5",
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 14,
            "docID": "S100FVO7",
            "edinetCode": "E06748",
            "secCode": null,
            "JCN": "2010001049257",
            "filerName": "大和証券投資信託委託株式会社",
            "fundCode": "G04644",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-09-11",
            "periodEnd": "2019-03-11",
            "submitDateTime": "2019-06-04 09:04",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第27期(平成30年9月11日－平成31年3月11日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 15,
            "docID": "S100FTPP",
            "edinetCode": "E08957",
            "secCode": null,
            "JCN": "4010401049128",
            "filerName": "三井住友ＤＳアセットマネジメント株式会社",
            "fundCode": "G13353",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-03-06",
            "periodEnd": "2019-03-04",
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第3期(平成30年3月6日－平成31年3月4日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 16,
            "docID": "S100FVO9",
            "edinetCode": "E06748",
            "secCode": null,
            "JCN": "2010001049257",
            "filerName": "大和証券投資信託委託株式会社",
            "fundCode": "G04644",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 17,
            "docID": "S100FQ36",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G03666",
            "ordinanceCode": "030",
            "formCode": "04A000",
            "docTypeCode": "030",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "有価証券届出書（内国投資信託受益証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 18,
            "docID": "S100FVRG",
            "edinetCode": "E12460",
            "secCode": null,
            "JCN": "7010001054021",
            "filerName": "野村アセットマネジメント株式会社",
            "fundCode": "G09073",
            "ordinanceCode": "030",
            "formCode": "995000",
            "docTypeCode": "180",
            "periodStart": null,
            "periodEnd": null,
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "臨時報告書（内国特定有価証券）",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": "第29条第2項第4号",
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "0",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 19,
            "docID": "S100FMNN",
            "edinetCode": "E12441",
            "secCode": null,
            "JCN": "3010001062358",
            "filerName": "岡三アセットマネジメント株式会社",
            "fundCode": "G10603",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-09-08",
            "periodEnd": "2019-03-07",
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第9期(平成30年9月8日－平成31年3月7日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        },
        {
            "seqNumber": 20,
            "docID": "S100FTVR",
            "edinetCode": "E08957",
            "secCode": null,
            "JCN": "4010401049128",
            "filerName": "三井住友ＤＳアセットマネジメント株式会社",
            "fundCode": "G13350",
            "ordinanceCode": "030",
            "formCode": "07A000",
            "docTypeCode": "120",
            "periodStart": "2018-03-06",
            "periodEnd": "2019-03-04",
            "submitDateTime": "2019-06-04 09:05",
            "docDescription": "有価証券報告書（内国投資信託受益証券）－第3期(平成30年3月6日－平成31年3月4日)",
            "issuerEdinetCode": null,
            "subjectEdinetCode": null,
            "subsidiaryEdinetCode": null,
            "currentReportReason": null,
            "parentDocID": null,
            "opeDateTime": null,
            "withdrawalStatus": "0",
            "docInfoEditStatus": "0",
            "disclosureStatus": "0",
            "xbrlFlag": "1",
            "pdfFlag": "1",
            "attachDocFlag": "1",
            "englishDocFlag": "0"
        }
]}
"""
